---
apiVersion: v1
kind: Namespace
metadata:
  name: cadang-ns
  labels:
    app: cadangapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadang-deploy
  labels:
    app: cadangapp
  namespace: cadang-ns

spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 30%
      maxSurge: 30%
  selector:
    matchLabels:
      app: cadangapp
  template:
    metadata:
      labels:
        name: cadang-po
        app: cadangapp
      namespace: cadang-ns
    spec:
      containers:
        - name: cadangapp-container
          image: kkkkkwannn/day2workshop:v1.2
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
            - name: INSTANCE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: web-port
              containerPort: 3000
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: cadang-svc
  namespace: cadang-ns
  labels:
    app: cadangapp
spec:
  type: ClusterIP
  selector:
    app: cadangapp
    name: cadang-po
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: web-port
