---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bgg-ns
  labels:
    app: bggapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bggapp
  template:
    metadata:
      labels:
        app: bggapp
    spec:
      containers:
        - name: bggapp-container
          image: chukmunnlee/bgg-app:nov-2025
          imagePullPolicy: IfNotPresent
          env:
            - name: BGG_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: bgg-config
                  key: BGG_DB_HOST
            - name: BGG_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: bgg-config
                  key: BGG_DB_USER
            - name: BGG_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: bgg-config
                  key: BGG_DB_PASSWORD
          ports:
            - name: http
              containerPort: 5000
          resources:
            requests:
              memory: "96Mi"
              cpu: "64m"
            limits:
              memory: "96Mi"
              cpu: "64m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bgg-ns
  labels:
    app: bggapp
spec:
  type: ClusterIP
  selector:
    app: bggapp
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bggapp-ing
  namespace: bgg-ns
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: bgg-139.59.222.9.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bggapp-svc
                port:
                  number: 5000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bggapp-hpa
  namespace: bgg-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bggapp-deploy
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
