---
apiVersion: v1
kind: Namespace
metadata:
  name: bgg-ns
  labels:
    app: bggdb

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-config
  namespace: bgg-ns
data:
  BGG_DB_USER: "root"
  BGG_DB_PASSWORD: "mydbpassword"
  BGG_DB_HOST: "bggdb-svc"
  BGG_PORT: "5000"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bggdb-pvc
  namespace: bgg-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bgg-ns
  labels:
    app: bggdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bggdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bggdb
    spec:
      containers:
        - name: bggdb-container
          image: chukmunnlee/bgg-database:nov-2025
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: bggdb-config
                  key: BGG_DB_PASSWORD
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: data-vol
              mountPath: /var/lib/mysql
      volumes:
        - name: data-vol
          persistentVolumeClaim:
            claimName: bggdb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bgg-ns
  labels:
    app: bggdb
spec:
  type: ClusterIP
  selector:
    app: bggdb
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
